name: r-for-ds
channels:
  - conda-forge
  - defaults
dependencies:
  - r-base
  - r-tidyverse
  - r-ggthemes
  - r-palmerpenguins
  - r-nycflights13
  - r-languageserver
  - ipykernel
  - r-irkernel
